// Command gendocs generates documentation from source code.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

type ErrorCode struct {
	Code        string
	Description string
}

func main() {
	// Parse apperr.go file
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "internal/apperr/apperr.go", nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing apperr.go: %v\n", err)
		os.Exit(1)
	}

	var codes []ErrorCode

	// Find all constant declarations
	ast.Inspect(file, func(n ast.Node) bool {
		decl, ok := n.(*ast.GenDecl)
		if !ok || decl.Tok != token.CONST {
			return true
		}

		for _, spec := range decl.Specs {
			vspec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}

			for i, name := range vspec.Names {
				// Get the comment
				var comment string
				if vspec.Comment != nil && len(vspec.Comment.List) > i {
					comment = strings.TrimSpace(vspec.Comment.List[i].Text)
					comment = strings.TrimPrefix(comment, "//")
					comment = strings.TrimSpace(comment)
				}

				// Try to get the string literal value
				var codeValue string
				if lit, ok := vspec.Values[i].(*ast.BasicLit); ok && lit.Kind == token.STRING {
					codeValue = strings.Trim(lit.Value, "\"")
				}

				if codeValue != "" {
					codes = append(codes, ErrorCode{
						Code:        codeValue,
						Description: comment,
					})
				}
			}
		}
		return true
	})

	// Sort by code
	sort.Slice(codes, func(i, j int) bool {
		return codes[i].Code < codes[j].Code
	})

	// Generate Markdown
	var buf bytes.Buffer
	buf.WriteString("# Error Code Reference\n\n")
	buf.WriteString("This document lists all error codes used in newapi-tools.\n\n")
	buf.WriteString("| Code | Description |\n")
	buf.WriteString("|------|-------------|\n")

	for _, ec := range codes {
		desc := ec.Description
		if desc == "" {
			desc = "-"
		}
		buf.WriteString(fmt.Sprintf("| `%s` | %s |\n", ec.Code, desc))
	}

	buf.WriteString("\n")
	buf.WriteString("*Auto-generated by `make docs` or `go run cmd/gendocs/main.go`*\n")

	// Write to file
	outputPath := "docs/errors.md"
	if err := os.WriteFile(outputPath, buf.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", outputPath, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s successfully\n", outputPath)
}
