run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gocyclo
    - gosec

linters-settings:
  errcheck:
    check-type-assertions: false

  gocyclo:
    min-complexity: 40

  gosec:

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - linters:
        - gosec
      text: "G204"
    - linters:
        - gosec
      text: "G306"
    - linters:
        - gosec
      text: "G110"
    - linters:
        - gosec
      text: "G115"